# Generated by Django 4.0.3 on 2022-04-06 21:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
